@host = http://localhost:5276

### Backend alive
GET {{host}}/health
Accept: application/json

###

### Database connectivity
GET {{host}}/health/database
Accept: application/json

###

### MinIO connectivity (Degraded khi chưa đăng ký IMinioClient)
GET {{host}}/health/minio
Accept: application/json

###
