pipeline {
    agent any

    environment {
        REGISTRY = "localhost:5000"
        IMAGE_NAME = "bookstore/api"
        TAG = "latest"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                cd src/BE
                docker build \
                  -t $REGISTRY/$IMAGE_NAME:$TAG \
                  -f Core/BookStore.API/Dockerfile .
                '''
            }
        }

        stage('Login Registry') {
            steps {
                withCredentials([
                  usernamePassword(
                    credentialsId: 'registry-creds',
                    usernameVariable: 'REG_USER',
                    passwordVariable: 'REG_PASS'
                  )
                ]) {
                    sh 'echo $REG_PASS | docker login $REGISTRY -u $REG_USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $REGISTRY/$IMAGE_NAME:$TAG'
            }
        }
    }
}
