pipeline {
    agent any

    environment {
        REGISTRY = "registry.local:5000"
        IMAGE_NAME = "bookstore/api"
        TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Build Image') {
            steps {
                sh '''
                cd src/BE
                docker build \
                  -t $REGISTRY/$IMAGE_NAME:$TAG \
                  -f Core/BookStore.API/Dockerfile .
                '''
            }
        }

        stage('Login Registry') {
            steps {
                withCredentials([
                  usernamePassword(
                    credentialsId: 'registry-creds',
                    usernameVariable: 'REG_USER',
                    passwordVariable: 'REG_PASS'
                  )
                ]) {
                    sh 'echo $REG_PASS | docker login $REGISTRY -u $REG_USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $REGISTRY/$IMAGE_NAME:$TAG
                docker tag $REGISTRY/$IMAGE_NAME:$TAG $REGISTRY/$IMAGE_NAME:latest
                docker push $REGISTRY/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Cleanup') {
            steps {
                sh '''
                docker rmi $REGISTRY/$IMAGE_NAME:$TAG || true
                '''
            }
        }
    }
}
